// Generated by SolidPython 1.0.5 on 2021-02-24 17:26:32


union() {
	difference() {
		polyhedron(faces = [[0, 1, 2, 3], [4, 5, 1, 0], [7, 6, 5, 4], [5, 6, 2, 1], [6, 7, 3, 2], [7, 4, 0, 3]], points = [[0, 0, 0], [150, 0, 0], [150, 30, 0], [0, 30, 0], [3.5000000000, 3.5000000000, 10], [146.5000000000, 3.5000000000, 10], [146.5000000000, 26.5000000000, 10], [3.5000000000, 26.5000000000, 10]]);
		rotate(a = [70.7099537808, 0, 0]) {
			translate(v = [18.7500000000, 1.2500000000, -1]) {
				linear_extrude(height = 2) {
					scale(v = [0.0900000000, 0.0900000000, 0.0900000000]) {
						import(file = "gitlab.svg", origin = [0, 0]);
					}
				}
			}
		}
	}
	rotate(a = [70.7099537808, 0, 0]) {
		translate(v = [37.5000000000, 3.2500000000, -1.5000000000]) {
			linear_extrude(height = 2) {
				text(size = 5, text = "@felixgomez");
			}
		}
	}
	rotate(a = [70.7099537808, 0, 0]) {
		translate(v = [120.0000000000, 2.2500000000, -1.5000000000]) {
			linear_extrude(height = 2) {
				text(size = 6, text = "2020");
			}
		}
	}
	union() {
		translate(v = [8.5000000000, 16.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 0.9090909091]);
		}
		translate(v = [13.5000000000, 6.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 2.7272727273]);
		}
		translate(v = [21.0000000000, 11.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 0.9090909091]);
		}
		translate(v = [21.0000000000, 13.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 1.8181818182]);
		}
		translate(v = [31.0000000000, 11.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 0.9090909091]);
		}
		translate(v = [31.0000000000, 16.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 10.0000000000]);
		}
		translate(v = [36.0000000000, 6.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 8.1818181818]);
		}
		translate(v = [36.0000000000, 8.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 0.9090909091]);
		}
		translate(v = [38.5000000000, 6.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 0.9090909091]);
		}
		translate(v = [38.5000000000, 8.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 2.7272727273]);
		}
		translate(v = [38.5000000000, 16.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 13.6363636364]);
		}
		translate(v = [38.5000000000, 18.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 5.4545454545]);
		}
		translate(v = [41.0000000000, 6.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 5.4545454545]);
		}
		translate(v = [41.0000000000, 8.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 11.8181818182]);
		}
		translate(v = [41.0000000000, 11.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 8.1818181818]);
		}
		translate(v = [41.0000000000, 13.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 0.9090909091]);
		}
		translate(v = [41.0000000000, 16.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 1.8181818182]);
		}
		translate(v = [43.5000000000, 8.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 3.6363636364]);
		}
		translate(v = [46.0000000000, 8.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 6.3636363636]);
		}
		translate(v = [46.0000000000, 11.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 1.8181818182]);
		}
		translate(v = [46.0000000000, 16.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 0.9090909091]);
		}
		translate(v = [48.5000000000, 8.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 0.9090909091]);
		}
		translate(v = [48.5000000000, 11.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 1.8181818182]);
		}
		translate(v = [48.5000000000, 13.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 1.8181818182]);
		}
		translate(v = [51.0000000000, 8.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 3.6363636364]);
		}
		translate(v = [51.0000000000, 11.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 4.5454545455]);
		}
		translate(v = [53.5000000000, 6.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 2.7272727273]);
		}
		translate(v = [53.5000000000, 11.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 6.3636363636]);
		}
		translate(v = [53.5000000000, 13.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 1.8181818182]);
		}
		translate(v = [53.5000000000, 18.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 0.9090909091]);
		}
		translate(v = [56.0000000000, 6.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 4.5454545455]);
		}
		translate(v = [56.0000000000, 8.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 3.6363636364]);
		}
		translate(v = [56.0000000000, 11.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 5.4545454545]);
		}
		translate(v = [56.0000000000, 13.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 1.8181818182]);
		}
		translate(v = [56.0000000000, 16.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 9.0909090909]);
		}
		translate(v = [58.5000000000, 6.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 6.3636363636]);
		}
		translate(v = [58.5000000000, 8.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 1.8181818182]);
		}
		translate(v = [58.5000000000, 11.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 3.6363636364]);
		}
		translate(v = [58.5000000000, 13.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 5.4545454545]);
		}
		translate(v = [58.5000000000, 16.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 0.9090909091]);
		}
		translate(v = [63.5000000000, 6.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 0.9090909091]);
		}
		translate(v = [63.5000000000, 8.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 1.8181818182]);
		}
		translate(v = [66.0000000000, 16.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 0.9090909091]);
		}
		translate(v = [68.5000000000, 6.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 1.8181818182]);
		}
		translate(v = [71.0000000000, 13.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 2.7272727273]);
		}
		translate(v = [73.5000000000, 6.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 2.7272727273]);
		}
		translate(v = [73.5000000000, 8.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 5.4545454545]);
		}
		translate(v = [73.5000000000, 11.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 0.9090909091]);
		}
		translate(v = [76.0000000000, 6.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 2.7272727273]);
		}
		translate(v = [76.0000000000, 8.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 3.6363636364]);
		}
		translate(v = [76.0000000000, 11.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 6.3636363636]);
		}
		translate(v = [81.0000000000, 13.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 1.8181818182]);
		}
		translate(v = [83.5000000000, 6.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 1.8181818182]);
		}
		translate(v = [83.5000000000, 8.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 1.8181818182]);
		}
		translate(v = [83.5000000000, 11.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 0.9090909091]);
		}
		translate(v = [86.0000000000, 6.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 10.0000000000]);
		}
		translate(v = [86.0000000000, 8.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 0.9090909091]);
		}
		translate(v = [86.0000000000, 11.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 12.7272727273]);
		}
		translate(v = [86.0000000000, 13.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 1.8181818182]);
		}
		translate(v = [88.5000000000, 6.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 4.5454545455]);
		}
		translate(v = [91.0000000000, 16.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 10.0000000000]);
		}
		translate(v = [93.5000000000, 6.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 1.8181818182]);
		}
		translate(v = [93.5000000000, 8.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 0.9090909091]);
		}
		translate(v = [93.5000000000, 11.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 0.9090909091]);
		}
		translate(v = [96.0000000000, 8.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 0.9090909091]);
		}
		translate(v = [96.0000000000, 16.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 1.8181818182]);
		}
		translate(v = [101.0000000000, 8.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 0.9090909091]);
		}
		translate(v = [101.0000000000, 13.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 2.7272727273]);
		}
		translate(v = [101.0000000000, 16.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 5.4545454545]);
		}
		translate(v = [101.0000000000, 18.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 0.9090909091]);
		}
		translate(v = [103.5000000000, 13.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 1.8181818182]);
		}
		translate(v = [103.5000000000, 16.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 4.5454545455]);
		}
		translate(v = [106.0000000000, 6.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 2.7272727273]);
		}
		translate(v = [106.0000000000, 16.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 1.8181818182]);
		}
		translate(v = [108.5000000000, 6.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 3.6363636364]);
		}
		translate(v = [108.5000000000, 11.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 2.7272727273]);
		}
		translate(v = [108.5000000000, 16.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 20.0000000000]);
		}
		translate(v = [116.0000000000, 11.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 0.9090909091]);
		}
		translate(v = [116.0000000000, 18.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 3.6363636364]);
		}
		translate(v = [116.0000000000, 21.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 0.9090909091]);
		}
		translate(v = [118.5000000000, 6.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 6.3636363636]);
		}
		translate(v = [118.5000000000, 11.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 6.3636363636]);
		}
		translate(v = [118.5000000000, 13.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 6.3636363636]);
		}
		translate(v = [121.0000000000, 6.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 13.6363636364]);
		}
		translate(v = [121.0000000000, 13.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 2.7272727273]);
		}
		translate(v = [121.0000000000, 21.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 4.5454545455]);
		}
		translate(v = [123.5000000000, 6.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 7.2727272727]);
		}
		translate(v = [123.5000000000, 8.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 4.5454545455]);
		}
		translate(v = [123.5000000000, 11.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 0.9090909091]);
		}
		translate(v = [128.5000000000, 11.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 1.8181818182]);
		}
		translate(v = [128.5000000000, 13.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 8.1818181818]);
		}
		translate(v = [131.0000000000, 6.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 9.0909090909]);
		}
		translate(v = [131.0000000000, 13.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 10.9090909091]);
		}
		translate(v = [131.0000000000, 16.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 1.8181818182]);
		}
		translate(v = [133.5000000000, 13.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 3.6363636364]);
		}
		translate(v = [133.5000000000, 18.5000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 2.7272727273]);
		}
		translate(v = [138.5000000000, 6.0000000000, 10]) {
			cube(size = [2.5000000000, 2.5000000000, 0.9090909091]);
		}
	}
}
/***********************************************
*********      SolidPython code:      **********
************************************************
 
#!/usr/bin/env python3

import argparse
import asyncio
import datetime
import math
import subprocess
from calendar import monthrange

import aiohttp
from bs4 import BeautifulSoup
from solid import *
from solid.utils import *

__author__ = "Félix Gómez"


async def get_contributions(semaphore, domain, username, date, contribution_matrix):
    """Get contributions directly using Gitlab activities endpoint API (asynchronously)"""
    async with aiohttp.ClientSession(raise_for_status=True) as client:
        try:
            date_as_str = date.strftime("%Y-%m-%d")
            url = domain + '/users/' + username + '/calendar_activities?date=' + date_as_str
            async with semaphore, client.get(url) as response:
                content = await response.text()
                soup = BeautifulSoup(content, 'html.parser')
                contribution_matrix.append(
                    [int(date.strftime('%j')), int(date.strftime('%u')) - 1, len(soup.find_all('li'))])

        except Exception as err:
            print(f"Exception occured: {err}")
            pass


def all_dates_in_year(year=2020):
    for month in range(1, 13):
        for day in range(1, monthrange(year, month)[1] + 1):
            yield datetime.datetime(year, month, day)


def parse_contribution_matrix(contribution_matrix):
    day_offset = sorted(contribution_matrix, key=lambda x: x[0])[0][1]
    max_contributions_by_day = sorted(contribution_matrix, key=lambda x: x[2], reverse=True)[0][2]
    ordered_contribution_matrix = sorted(contribution_matrix, key=lambda x: x[0])
    year_contribution_list = [row.pop(2) for row in ordered_contribution_matrix]

    for i in range(day_offset):
        year_contribution_list.insert(0, 0)

    return [year_contribution_list, max_contributions_by_day]


def generate_skyline_stl(username, year, contribution_matrix):
    year_contribution_list, max_contributions_by_day = parse_contribution_matrix(contribution_matrix)

    base_top_width = 23
    base_width = 30
    base_length = 150
    base_height = 10
    max_length_contributionbar = 20
    bar_base_dimension = 2.5

    base_top_offset = (base_width - base_top_width) / 2
    face_angle = math.degrees(math.atan(base_height / base_top_offset))

    base_points = [
        [0, 0, 0],
        [base_length, 0, 0],
        [base_length, base_width, 0],
        [0, base_width, 0],
        [base_top_offset, base_top_offset, base_height],
        [base_length - base_top_offset, base_top_offset, base_height],
        [base_length - base_top_offset, base_width - base_top_offset, base_height],
        [base_top_offset, base_width - base_top_offset, base_height]
    ]

    base_faces = [
        [0, 1, 2, 3],  # bottom
        [4, 5, 1, 0],  # front
        [7, 6, 5, 4],  # top
        [5, 6, 2, 1],  # right
        [6, 7, 3, 2],  # back
        [7, 4, 0, 3]  # left
    ]

    base_scad = polyhedron(points=base_points, faces=base_faces)

    year_scad = rotate([face_angle, 0, 0])(
        translate([base_length - base_length / 5, base_height / 2 - base_top_offset / 2 - 1, -1.5])(
            linear_extrude(height=2)(
                text(str(year), 6)
            )
        )
    )

    user_scad = rotate([face_angle, 0, 0])(
        translate([base_length / 4, base_height / 2 - base_top_offset / 2, -1.5])(
            linear_extrude(height=2)(
                text("@" + username, 5)
            )
        )
    )

    logo_gitlab_scad = rotate([face_angle, 0, 0])(
        translate([base_length / 8, base_height / 2 - base_top_offset / 2 - 2, -1])(
            linear_extrude(height=2)(
                scale([0.09, 0.09, 0.09])(
                    import_stl("gitlab.svg")
                )
            )
        )
    )

    bars = None

    week_number = 1
    for i in range(len(year_contribution_list)):

        day_number = i % 7
        if day_number == 0:
            week_number += 1

        if year_contribution_list[i] == 0:
            continue

        bar = translate(
            [base_top_offset + 2.5 + (week_number - 1) * bar_base_dimension,
             base_top_offset + 2.5 + day_number * bar_base_dimension, base_height])(
            cube([bar_base_dimension, bar_base_dimension,
                  year_contribution_list[i] * max_length_contributionbar / max_contributions_by_day])
        )

        if bars is None:
            bars = bar
        else:
            bars += bar

    scad_contributions_filename = 'gitlab_' + username + '_' + str(year)
    scad_skyline_object = base_scad - logo_gitlab_scad + user_scad + year_scad

    if bars is not None:
        scad_skyline_object += bars

    scad_render_to_file(scad_skyline_object,
                        scad_contributions_filename + '.scad')

    subprocess.run(['openscad', '-o', scad_contributions_filename + '.stl', scad_contributions_filename + '.scad'],
                   capture_output=True)

    print('Generated STL file ' + scad_contributions_filename +
          '.stl')


def main():
    parser = argparse.ArgumentParser(prog="gitlab-skyline", description='Create STL from Gitlab contributions',
                                     epilog='Enjoy!')
    parser.add_argument('--domain', metavar=None, type=str, nargs="?", help='GitlabEE/CE custom domain',
                        default='https://gitlab.com')
    parser.add_argument('username', metavar=None, type=str, help='Gitlab username (without @)')
    parser.add_argument('year', metavar=None, type=int,
                        help='Year of contributions to fetch', default=2020, nargs="?")

    parser.add_argument('--max_requests', metavar=None, type=int,
                        help='Max. simultaneous requests to Gitlab. Don\'t mess with their server!', default=10,
                        nargs="?")

    args = parser.parse_args()

    domain = args.domain
    username = args.username
    max_requests = args.max_requests
    year = args.year
    contribution_matrix = []

    print("Fetching contributions from Gitlab...")

    semaphore = asyncio.Semaphore(max_requests)
    loop = asyncio.get_event_loop()
    loop.run_until_complete(
        asyncio.wait(
            [get_contributions(semaphore, domain, username, date, contribution_matrix) for date in
             all_dates_in_year(year)]))
    loop.close()

    print("Generating STL...")
    generate_skyline_stl(username, year, contribution_matrix)


if __name__ == '__main__':
    main()
 
 
************************************************/
